### PR TITLE
Added logic to specify singular timescales

### PR DESCRIPTION
**Pull request by AlexDeGruvenB**
A little thing that's been bugging me since I started using the extension, it doesn't adapt the time-scale to singular or plural.

Ex:
An item was first seen 2 minutes ago, extension reports "First Seen: 2 mins ago".
An item was first seen 1 minute ago, extension reports "First Seen : 1 mins ago".

I tried to figure out how to wedge that logic into a switch/case block, but it wasn't working in my head. I may still think about this more.

### CODE REVIEW

**Comment by FMaz008** [comment]
It might be a good opportunity to use a conditional ternary operator to keep the code brief/concise :)

**Comment by crysallis** [comment]
I could suggest a rewrite of the function itself that should work as well
```js
function timeSince(timenow, date) {
	const units = [
		{ value: 31536000, unit: "year" },
		{ value: 2592000, unit: "month" },
		{ value: 86400, unit: "day" },
		{ value: 3600, unit: "hr" },
		{ value: 60, unit: "min" },
		{ value: 1, unit: "sec" } 
	];
 
	var seconds = Math.floor((timenow - date) / 1000);
 
	for (const {value, unit} of units) { 
		const interval = seconds / value;
		if (interval >= 1) {
			const plural = Math.floor(interval) > 1 ? 's' : '';
			return Math.floor(interval) + ` ${unit}${plural}`;
		}
	}
 }
 ```

**Comment by crysallis** [comment]
```js
function timeSince(timenow, date) {
	const units = [
		{ value: 31536000, unit: "year" },
		{ value: 2592000, unit: "month" },
		{ value: 86400, unit: "day" },
		{ value: 3600, unit: "hr" },
		{ value: 60, unit: "min" },
		{ value: 1, unit: "sec" } 
	];
 
	var seconds = Math.floor((timenow - date) / 1000);
 
	for (const {value, unit} of units) { 
		const interval = seconds / value;
		console.log(interval);
		if (interval >= 1) {
			const plural = Math.floor(interval) > 1 ? 's' : '';
			return Math.floor(interval) + ` ${unit}${plural}`;
		}
	}
	return `${Math.floor(seconds)} secs`;
 }
 ```
 
 should account for issue as well

**Comment by AlexDeGruvenB** [comment]
So I went deeper on this than I expected and ended up with this:

function timeSince(timenow, date) {
    var seconds = Math.floor((timenow - date) / 1000);
    var interval = seconds / 31536000;
    var numberof = 0;

    return (interval > 1) ? ((numberof = Math.floor(interval)) + (numberof === 1 ? " year" : " years")) :
        (interval = seconds / 2592000) > 1 ? ((numberof = Math.floor(interval)) + (numberof === 1 ? " month" : " months")) :
        (interval = seconds / 86400) > 1 ? ((numberof = Math.floor(interval)) + (numberof === 1 ? " day" : " days")) :
        (interval = seconds / 3600) > 1 ? ((numberof = Math.floor(interval)) + (numberof === 1 ? " hour" : " hrs")) :
        (interval = seconds / 60) > 1 ? ((numberof = Math.floor(interval)) + (numberof === 1 ? " min" : " mins")) :
        (Math.floor(seconds) === 1 ? (Math.floor(seconds) + " sec") : (Math.floor(seconds) + " secs"));
}

**Review by FMaz008 — APPROVED** [review]

**Pull request merged**
