### PR TITLE
[QOL] Snap to top of page on hideAllItems call

### PR DESCRIPTION
**Pull request by BenB33**
Hiding all items currently leaves you at the bottom of the page.
I find myself scrolling to the top after every use.

I believe this change is a great quality of life change.

### CODE REVIEW

**Review by Tablecloths — APPROVED** [review]

**Comment by FMaz008** [comment]
I'm  a little confused when you say it "leave you at the bottom of the page", using hideAll does not scroll at all, it keeps you at the same position you already were.

Am I to understand that you are not using the small items, so the items are the regular size, and naturally as *you* scroll down, and reach the bottom of the list, you hit hide all and then you're left in the footer area?

If that is the case, I would want the scroll to scroll up to the RFY tabs, not the complete top, as this, would be ultra annoying for someone like me with a small screen where scrolling up means I'm stuck looking at header content eveytime and would have to scroll down.

If you can detect the top-position of the RFY/AFA/AI tabs (which change depending on the stylesheet used) and scroll up to that amount, then that's a great idea.

**Comment by BenB33** [comment]
> I'm  a little confused when you say it "leave you at the bottom of the page", using hideAll does not scroll at all, it keeps you at the same position you already were.
> 
> 
> 
> Am I to understand that you are not using the small items, so the items are the regular size, and naturally as *you* scroll down, and reach the bottom of the list, you hit hide all and then you're left in the footer area?
> 
> 
> 
> If that is the case, I would want the scroll to scroll up to the RFY tabs, not the complete top, as this, would be ultra annoying for someone like me with a small screen where scrolling up means I'm stuck looking at header content eveytime and would have to scroll down.
> 
> 
> 
> If you can detect the top-position of the RFY/AFA/AI tabs (which change depending on the stylesheet used) and scroll up to that amount, then that's a great idea.

Sorry, I should've explained myself better.
Rather than leave you at the bottom of the page, it leaves you where you are. And as someone who uses the larger vanilla cards, when I scroll to the bottom of a full page on AI tab and click Hide All, my page is at the bottom, and I believe scrolling up would be more user friendly in that situation.

When I get home I'll adjust the scroll to snap to the RFY/AFA/AI headers.

**Comment by FMaz008** [comment]
I agree. I never thought about vanilla card. If we can make it go back to the RFY tabs that would make everyone happy I think :)

**Review by Tablecloths — APPROVED** [review]

**Comment by BenB33** [comment]
> I agree. I never thought about vanilla card. If we can make it go back to the RFY tabs that would make everyone happy I think :)

Made the change mentioned above.

**Pull request merged**
