### PR TITLE
Add category path to pinned tile in grid view

### PR DESCRIPTION
**Pull request by Wladefant**

### CODE REVIEW

**Comment by FMaz008** [comment]
Reading the code, I think it will show the category path for the current page, not the items that are pinned.

**Comment by Wladefant** [comment]
Yes, fixed that already, locally. It should have been a draft pull request.  I am exploring the code base a bit first

**Comment by FMaz008** [comment]
Ok perfect! 

We'll probably have to change some server side too so that it save the categories for people who have remote storage enabled.

**Comment by FMaz008** [comment]
Closed as this should have been a draft and does not include the proper fix. (New PR welcome :) )

**Pull request closed without merging**
